# Site Info
title: 공부를 합시다
tagline: '공부하자'
description: ''
baseurl: ""
url: http://gungadinn.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Pingu
  description: Pingu
  contact:
    #linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/gungadinn
    #twitter:   https://twitter.com/Li_Zhihao
    email:     ovo.pingu@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Categories:           
    - '/blog/categories/'
#    - { Categories: '/blog/categories/' }
#    - { Tags: '/blog/tags/' }
    - { python : '/blog/categories/#python' }
    - { data : '/blog/categories/#data' }
  About:          
    - '/about/'
#  Github Project: 
#    - 'http://codinfox.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/sky.jpeg
  caption: 개발을 잘 하고 싶어요

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'pingu' # leave blank if you don't want disqus

